### ISSUE TITLE
Update to iOS 9

### ISSUE THREAD

**Issue by diogot** [cheah/GoogleConversionTracking-iOS-SDK#4]
- Needed bitcode support

**Comment by niklassaers** [comment]
+1 3.15.0 is current version

**Comment by cheah** [comment]
Where do you find version 3.15.0 of the library?

The SDK from this [link](https://developers.google.com/app-conversion-tracking/ios/) is still 3.2.0, which is the same version in this repo.

**Comment by ou2s** [comment]
Any update about bitcode support?
